repository_type: pipeline

nf_core_version: 3.1.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - LICENSE
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - LICENSE
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fiberseq_local_logo_light.png
    - docs/images/nf-core-fiberseq_local_logo_light.png
    - docs/images/nf-core-fiberseq_local_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - assets/multiqc_config.yml
    - LICENSE
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .editorconfig
    - .prettierignore
    - .prettierrc.yml
    - CITATIONS.md
    - assets/multiqc_config.yml
    - LICENSE
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/ci.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fiberseq_local_logo_light.png
    - docs/images/nf-core-fiberseq_local_logo_light.png
    - docs/images/nf-core-fiberseq_local_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge

template:
  org: chaochaowong
  name: fiberseq_local
  description: local fiberseq pipeline at SCRI
  author: Chao-Jen Wong
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - ci
    - igenomes
    - github_badges
    - code_linters
    - citations
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - license
    - adaptivecard
    - slackreport
    - test_config
    - seqera_platform
    - rocrate
    - vscode
  is_nfcore: false
